openapi: 3.0.0
info:
  description: This is the API
  title: My API
  version: 1.0.0
servers:
- url: ""
paths:
  /api/workerStarted:
    post:
      description: report worker started and return shared file system settings
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/_api_workerStarted_post_request'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SharedFileSystemConfig'
          description: Exectable jobs
  /api/getExectableJob:
    post:
      description: Get executable job
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/_api_getExectableJob_post_200_response_inner'
                type: array
          description: Exectable jobs
      summary: Get a single user
  /api/jobFinished:
    post:
      description: report job finished
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/JobFinishedRequest'
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
          description: Exectable jobs
      summary: report job finished
  /api/jobFailed:
    post:
      description: report job failed
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/_api_jobFailed_post_request'
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
          description: Exectable jobs
      summary: report job failed
  /api/do_eval:
    post:
      description: report job failed
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/_api_do_eval_post_request'
      responses:
        "200":
          content:
            application/json:
              schema:
                nullable: true
          description: Exectable jobs
      summary: report job failed
components:
  parameters: {}
  schemas:
    SharedFileSystemConfig:
      example:
        endpoint: endpoint
        secretKey: secretKey
        accessKey: accessKey
        type: s3
        region: region
        rootUrl: https://openapi-generator.tech
      properties:
        type:
          enum:
          - s3
          - nfs
          type: string
        rootUrl:
          format: uri
          type: string
        region:
          type: string
        endpoint:
          type: string
        accessKey:
          type: string
        secretKey:
          type: string
      required:
      - rootUrl
      - type
      type: object
    CommandString:
      items:
        $ref: '#/components/schemas/CommandString_inner'
      type: array
    LoadListingEnum:
      enum:
      - no_listing
      - shallow_listing
      - deep_listing
      type: string
    OutputBinding:
      example:
        loadContents: true
        loadListing: null
        outputEval: outputEval
        name: name
        glob:
        - glob
        - glob
        secondaryFiles:
        - pattern: pattern
          requiredBoolean: true
          requiredString: requiredString
        - pattern: pattern
          requiredBoolean: true
          requiredString: requiredString
      properties:
        name:
          type: string
        secondaryFiles:
          items:
            $ref: '#/components/schemas/OutputBinding_secondaryFiles_inner'
          type: array
        loadContents:
          type: boolean
        loadListing:
          $ref: '#/components/schemas/LoadListingEnum'
        glob:
          items:
            type: string
          type: array
        outputEval:
          type: string
      required:
      - name
      - secondaryFiles
      type: object
    MapperEnt:
      example:
        staged: true
        type: File
        resolved: resolved
        target: target
      properties:
        resolved:
          type: string
        target:
          type: string
        type:
          enum:
          - File
          - Directory
          - CreateFile
          - CreateWritableFile
          - WritableFile
          - WritableDirectory
          type: string
        staged:
          type: boolean
      required:
      - resolved
      - staged
      - target
      - type
      type: object
    runtime:
      example:
        custom_net: custom_net
      properties:
        custom_net:
          type: string
      type: object
    JobFinishedRequest:
      example:
        isCwlOutput: true
        exitCode: 0
        id: id
        results:
          key: ""
      properties:
        id:
          type: string
        isCwlOutput:
          type: boolean
        exitCode:
          type: integer
        results:
          additionalProperties:
            nullable: true
          type: object
      required:
      - exitCode
      - id
      - isCwlOutput
      - results
      type: object
    _api_workerStarted_post_request:
      properties:
        hostname:
          type: string
        cpu:
          type: integer
        memory:
          description: memory in MB
          type: integer
      required:
      - cpu
      - hostname
      - memory
      type: object
    _api_getExectableJob_post_200_response_inner:
      example:
        stdout_path: stdout_path
        dockerImage: dockerImage
        runtime:
          custom_net: custom_net
        builderOutdir: builderOutdir
        env:
          key: env
        outputBaseDir: outputBaseDir
        networkaccess: true
        timelimit: 0
        inplace_update: true
        stderr_path: stderr_path
        cwd: cwd
        fileitems:
        - staged: true
          type: File
          resolved: resolved
          target: target
        - staged: true
          type: File
          resolved: resolved
          target: target
        stdin_path: stdin_path
        generatedlist:
        - staged: true
          type: File
          resolved: resolved
          target: target
        - staged: true
          type: File
          resolved: resolved
          target: target
        id: id
        dockerExec: dockerExec
        commands:
        - null
        - null
        outputBindings:
        - loadContents: true
          loadListing: null
          outputEval: outputEval
          name: name
          glob:
          - glob
          - glob
          secondaryFiles:
          - pattern: pattern
            requiredBoolean: true
            requiredString: requiredString
          - pattern: pattern
            requiredBoolean: true
            requiredString: requiredString
        - loadContents: true
          loadListing: null
          outputEval: outputEval
          name: name
          glob:
          - glob
          - glob
          secondaryFiles:
          - pattern: pattern
            requiredBoolean: true
            requiredString: requiredString
          - pattern: pattern
            requiredBoolean: true
            requiredString: requiredString
      properties:
        id:
          type: string
        commands:
          items:
            $ref: '#/components/schemas/CommandString'
          type: array
        stdin_path:
          type: string
        stdout_path:
          type: string
        stderr_path:
          type: string
        env:
          additionalProperties:
            type: string
          type: object
        cwd:
          type: string
        builderOutdir:
          type: string
        timelimit:
          type: integer
        outputBindings:
          items:
            $ref: '#/components/schemas/OutputBinding'
          type: array
        fileitems:
          items:
            $ref: '#/components/schemas/MapperEnt'
          type: array
        generatedlist:
          items:
            $ref: '#/components/schemas/MapperEnt'
          type: array
        inplace_update:
          type: boolean
        networkaccess:
          type: boolean
        outputBaseDir:
          type: string
        dockerExec:
          type: string
        dockerImage:
          type: string
        runtime:
          $ref: '#/components/schemas/runtime'
      required:
      - builderOutdir
      - commands
      - cwd
      - env
      - fileitems
      - generatedlist
      - id
      - inplace_update
      - networkaccess
      - outputBindings
      - runtime
      type: object
    _api_jobFailed_post_request:
      properties:
        id:
          type: string
        errorMsg:
          type: string
      required:
      - errorMsg
      - id
      type: object
    _api_do_eval_post_request:
      properties:
        id:
          type: string
        ex:
          type: string
        exitCode:
          type: integer
        context:
          nullable: true
      required:
      - ex
      - id
      type: object
    CommandString_inner:
      properties:
        type:
          enum:
          - Key
          - Literal
          type: string
        value:
          type: string
      required:
      - type
      - value
      type: object
    OutputBinding_secondaryFiles_inner:
      example:
        pattern: pattern
        requiredBoolean: true
        requiredString: requiredString
      properties:
        pattern:
          type: string
        requiredBoolean:
          type: boolean
        requiredString:
          type: string
      required:
      - pattern
      type: object
